version: '3.8'

services:
  frontend:
    image: frontend-project
    ports:
    - 5001:5001
    container_name: frontend
    
  
  backend:
    image: backend-project
    ports:
      - 8001:8001
    container_name: backend

